# Generated by Django 4.2.3 on 2023-09-06 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "Male"), (2, "Female"), (3, "other")]
                    ),
                ),
                ("password", models.CharField(max_length=200)),
                ("profile", models.ImageField(upload_to="images/")),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
        ),
    ]
