# Generated by Django 4.2.3 on 2023-09-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
