# Generated by Django 4.2.3 on 2023-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0002_alter_users_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="country",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
