# Generated by Django 4.2.6 on 2024-02-21 11:34

import apps.userApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_users_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(upload_to=apps.userApp.models.path_and_rename),
        ),
    ]
