# Generated by Django 4.2.6 on 2024-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_alter_users_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile',
        ),
        migrations.AddField(
            model_name='users',
            name='pic',
            field=models.URLField(blank=True, default='http://test.com', null=True),
        ),
    ]
