# Generated by Django 4.2.6 on 2024-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_remove_users_profile_users_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
